# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='study_nums',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
