# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tap',
            field=models.CharField(default='', max_length=100, verbose_name='课程标签'),
        ),
    ]
