# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tap',
            new_name='tag',
        ),
    ]
